spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atguigudb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: mp-service
mybatis-plus:
  type-aliases-package: com.potato.mp.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
knife4j:
  enable: true
  openapi:
    title: 员工管理接口文档
    description: "员工管理接口文档"
    concat: rae
    url: https://www.abc.com
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.potato.mp.controller
server:
  port: 7700